---
title: "Analysis of grouped count data in a longitudinal study with an application in flowering of sweet orange"
author: "Prof. Idemauro A. R. de Lara (ESALQ/USP)"
date: "28 de Abril de 2016 - 14h - LEG - Sala 232"
#key-words: "Generalized Additive Models, GAMLSS."
output:
  pdf_document:
    template: template.tex
---

<!-- Escreva aqui o resumo do seminário. -->

The orange variety “x11” is a spontaneous mutant of sweet orange and 
has the property of a short juvenile period with early flowering. The 
data this work, refer to a randomized design, intending to assess the 
plants' flowering when grafted on to two varieties of rootstock. On 
each occasion, the number of branches per plant was counted and 
classified into four mutually exclusive flowering categories. We used 
the methodology of Generalized Linear Mixed Models to allow for 
excessive heterogeneity and include serial dependence among 
observations from the same plant. The results showed that there are 
significant differences in the classification of branches over the four 
seasons, with an interaction between season and branch categorizations.

<!------------------------------------------- -->
